### ISSUE TITLE
Head is null condition

### ISSUE THREAD

**Issue by faraznaqvi99** [RaffayHusayn/CustomLinkedList#1]
Wouldn't it be better if we checked if the head is not null instead of checking if it is null? Because head is only null in case of the first insertion, so why check it again and again.

**Comment by RaffayHusayn** [comment]
Are you suggesting we do the following?
```
if (head != null){
            Node tempNode = head;
            while (tempNode.next != null){
            tempNode = tempNode.next;
           }
           tempNode.next = node;
       }
       else{
           head = node;
       }
```
It works but I am having trouble understanding why would it be more efficient?
